version: '3'
services:
    web:
        build: .
        # image: "paradox:latest"
        environment:
            - JIRA_API=${JIRA_API}
            - JIRA_USERNAME=${JIRA_USERNAME}
            - JIRA_PASSWORD=${JIRA_PASSWORD}
        ports:
         - "0.0.0.0:5000:5000"
